#+title: Bienvenida a mis dotfiles

* Acerca de

Este repositorio contiene mis 'doftiles', que son archivos de texto donde se guardan configuraciones para algunos programas, window managers y shells de terminal. En Linux es posible configurar muchas aplicaciones mediante estos archivos, haciendo la configuración más portable y fácil de darle seguimiento de versiones. Para ello utilizo GNU Stow y Git.

Git es para el control de versiones, pero Stow es para organizar mejor este repositorio. La ventaja de usar GNU Stow es que puedo separar los dotfiles entre cada uno de los programas, por lo que puedo elegir a qué programa le aplico su configuración. Incluso, podría tener múltiples configuraciones para el mismo programa y poder elegir cuál de todas usar.

Una peculiaridad de mis dotfiles es que comencé a separarlos en múltiples repositorios. Tras cierta cantidad de programas, se volvió insostenible mantener un monorepo que iba cambiando continuamente y en múltiples lugares. Por eso, decidí darle su propio repositorio a las configuraciones que son lo suficientemente grandes.

* Requerimientos
- Git
- GNU Stow

Ambos requerimientos son relativamente opcionales. *Git* se puede omitir parcialmente, ya que se puede descargar el repositorio en formato ~.zip~ desde el propio GitHub. También se puede prescindir de *GNU Stow*, debido a que puedes crear manualmente tus propios /symlinks/ (en español, enlaces simbólicos), u optar por la vía fácil de copiar los archivos a sus respectivas carpetas.

* Instalación
** Git

Primero asegurate de tener git instalado.

Después ejecuta este comando *dentro de tu directorio home*

#+begin_src bash

git clone https://github.com/Nekoffeedrinker/denis-dotfiles.git ~/.denisDotfiles/

#+end_src

*** Clonar subrepos

*NOTA:* Este es un workarround temporal. En el futuro, este proceso se realizará de manera diferente.

Debido a que hay repositorios individuales que se usan en estos dotfiles, hay que clonarlos por separado. Esto te dará la versión más actualizada de todos y los posicionará en su lugar correcto.

#+begin_src bash

cd ~/.denisDotfiles/
git clone https://github.com/Nekoffeedrinker/doomEmacs-dotfiles.git ./doomEmacs-repo/.config/doom
git clone https://github.com/Nekoffeedrinker/neovim-dotfiles.git ./neovim-repo/.config/nvim
git clone https://github.com/Nekoffeedrinker/niriWM-dotfiles.git ./niriWM-repo/.config/niri
git clone https://github.com/Nekoffeedrinker/mangoWM-dotfiles.git ./mangoWM-repo/.config/mango
git clone https://github.com/Nekoffeedrinker/noctalia-dotfiles.git ./noctalia-repo
#+end_src

Puedes omitir alguno de los repositorios si es que no deseas tener todos.

** GNU Stow

Lo primero que hay que hacer es posicionar el esta carpeta de /dotfiles/ dentro de nuestro /home directory/, el directorio de usuario, que en sistemas Linux lo podremos identificar como ~/home/username/~, o simplemente con la tilde (~/). Esto es porque la manera más sencilla de usar Stow es creando los enlaces afuera del directorio donde ejecutamos el programa.

Otra cuestión acerca de Stow es que no copiará ningún archivo org del tipo README (ejemplo: ~README-nvim.org~), por lo que estos solo vivirán en esta carpeta.

*Para entrar más en detalle, favor de consultar el final de este README.*

*** Instalar todas las configuraciones

Para instalar todas las configuraciones, ejecuta:

#+begin_src bash

stow *

#+end_src

Para quitar todos los /symlinks/ (y por lo tanto los /dotfiles/), usa:

#+begin_src bash

stow -D *

#+end_src


*** Instalar solo las configuraciones de 1 programa

Supongamos que quieres instalar *Neovim*. Primero identifica el en el repositorio el nombre de la carpeta, en este caso ~nvim~. A continuación, ejecuta el siguiente comando:

#+begin_src bash

stow nvim

#+end_src

Para quitar quitar los dotfiles de nvim, usar:

#+begin_src bash

stow -D nvim

#+end_src


