#+title: Configuración de Doom Emacs
#+auto_tangle: t

* Tabla de contenidos :toc:
- [[#comandos-básicos-de-configuración][Comandos Básicos de configuración]]
- [[#initel][init.el]]
  - [[#ui][UI]]
  - [[#editor][Editor]]
  - [[#terminal][Terminal]]
- [[#tangle-config-packages][Tangle config-packages]]
- [[#aspecto-visual][Aspecto visual]]
  - [[#tipografía][Tipografía]]
  - [[#tema][Tema]]
  - [[#numeración-de-lineas][Numeración de lineas]]
- [[#org-mode][Org-mode]]
  - [[#directorioscarpetas-de-org-mode][Directorios/carpetas de org-mode]]
  - [[#plugin-org-auto-tangle][Plugin: org-auto-tangle]]
- [[#comentarios-originales][Comentarios Originales]]
  - [[#config][Config]]
  - [[#packages][Packages]]

* Comandos Básicos de configuración
- *~doom doctor~*
  Diagnostica problemas en la configuración y puede sugerirte cómo solucionarlo.
- *~doom sync~*
  Sincronizar las configuraciones de Doom Emacs con Emacs. Activa módulos del
  ~init.el~, descarga paquetes del ~packages.el~, y verifica que no haya
  errores.
  OJO: no carga cosas que estén en ~config.el~, para eso se necesita reiniciar.
- *~doom gc~*
  Para limpiar los paquetes y módulos que no estén cargados.

* init.el
** UI
- Activar ~indent-guides~.
- Activar ~ligatures~.
- Activar ~smooth-scroll~.
- Activar ~treemacs~.
- Desactivar '+pretty' en ~vc-gutter~ porque me gustan los indicadores toscos.
** Editor
- Activar ~(format +onsave)~.
- Activar ~word-wrap~ (para lenguajes de programación).
** Terminal
De las cuatro disponibles (eshell, shell, term, vterm), elegí:
 - ~eshell~ porque es la que tiene más cosas. Está escrita en elisp, entiende
   comandos de Emacs nativamente, más dificil de usar, pero algunos programas de
   terminal no sirven.
 - ~vterm~ porque es un emulador de la terminal del sistema, por lo que es
   igualita a la que ya uso en Kitty.

* Tangle config-packages

#+begin_src elisp :tangle config.el

;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

#+end_src
#+begin_src elisp :tangle packages.el

;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el

#+end_src

* Aspecto visual

** Tipografía

Para Doom emacs, hay 5 variables para controlar las fuentes. A parte de la
fuente primaria, el resto son opcionales
- ~doom-font~ es fuente primaria (monoespaciada).
- ~doom-variable-pitch-font~ es una fuente que no es monoespaciada
- ~doom-big-font~ es la fuente utilizada para =doom-big-font-mode=. Este modo
  es útil para presentaciones o video streaming.
- ~doom-symbol-font~ para /símbolos.
- ~doom-serif-font~ para la fuente ~fixed-pitch-serif~ (no sé cómo usarla).

#+begin_src elisp :tangle config.el
(setq doom-font
        (font-spec
         :family "MonaspiceXe Nerd Font Mono"
         :size 16 :weight 'regular)
      doom-variable-pitch-font
        (font-spec
         :family "Public Sans"
         :size 18)
      doom-serif-font
        (font-spec
         :family "MonaspiceAr Nerd Font Mono"
         :size 16))

(custom-set-faces!
  '(italic
    :family "MonaspiceRn Nerd Font Mono"
    :slant italic))
#+end_src

Una función poderosa de emacs son los /faces/ que serían como estilos de fuente
que podemos configurar para ciertos casos. En la configuración de arriba, se
configuró una para que el texto en italicas tenga una fuente distinta.

** Tema

Luego de instalar un tema, o elegir uno de los que trae doom, hay que cargarlo
usando ~doom-theme~ en la configuración. O también, puedes cargarlo usando
=M-x load-theme=, pero este sólo estará temporalmente.

#+begin_src elisp :tangle packages.el
(package! catppuccin-theme)
#+end_src

#+begin_src elisp :tangle config.el
(setq doom-theme 'catppuccin)
#+end_src

Otros temas que he probado son:

#+begin_src elisp :tangle-no

; doom-palenight         ; Predeterminado pero poquito mejor
; doom-nord              ; Muy gris para mí
; doom-wilmersdorf       ; El mejor org, pero lo demás lo resalta gris
; doom-spacegrey         ; Muy gris, Buen naranja, pero no resalta org
; doom-moonlight         ; Buen org, no me gusta el ambiente morado
; doom-opera-light       ; Tema claro
; doom-monokai-spectrum  ; Tema oscuro
; doom-monokai-pro       ; Tema oscuro
; doom-tokyo-night       ; Tema oscuro
; doom-oceanic-next      ; Tema oscuro

; doom-flatwhite         ; Tema claro
; doom-material-dark     ; Tema oscuro
; doom-tomorrow-day      ; Tema claro
; doom-tomorrow-night    ; Buen color, org no me convence

#+end_src

** Numeración de lineas

Es posible elegir entre tres modos de numeración de lineas
- ~nil~ desactivado
- ~t~ numeración absoluta
- ~'relative~ numeración relativa al cursor

#+begin_src elisp :tangle config.el
(setq display-line-numbers-type 'relative)
#+end_src

Notar que para la numeración relativa hay que anteponer una comilla simple.

* Org-mode

** Directorios/carpetas de org-mode

Los directorios y su función son:
 - ~org-directory~ donde se guardan los archivos org por defecto. En mi caso
   lo utilizo para las notas jerárquicas. Debe de ponerse antes de cargar org.

#+begin_src elisp :tangle config.el
(setq org-directory "~/Documents/Emacs/Notas")
#+end_src

** Plugin: org-auto-tangle

Se trata de un plugin que automatiza la acción de 'org-babel-tangle'

#+begin_src elisp :tangle packages.el
(package! org-auto-tangle)
#+end_src

#+begin_src elisp :tangle config.el
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))
#+end_src


* Comentarios Originales
** Config

#+begin_src elisp :tangle-no

;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `with-eval-after-load' block, otherwise Doom's defaults may override your
;; settings. E.g.
;;
;;   (with-eval-after-load 'PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look them up).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

#+end_src

** Packages

#+begin_src elisp :tangle-no

;; To install a package:
;;
;;   1. Declare them here in a `package!' statement,
;;   2. Run 'doom sync' in the shell,
;;   3. Restart Emacs.
;;
;; Use 'C-h f package\!' to look up documentation for the `package!' macro.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)

#+end_src

