cursor #171c1e
cursor_text_color #40484b

foreground            #171c1e
background            #f5fafd
selection_foreground  #ffffff
selection_background  #b2cad3
url_color             #00677c

color0   #0f1416
color1   #790029
color2   #005f09
color3   #998e00
color4   #006c82
color5   #95cfdb
color6   #00677c
color7   #202323
color8   #666b6c
color9   #c63c55
color10  #008c0d
color11  #a59a00
color12  #0c7a92
color13  #95cfdb
color14  #5093a1
color15  #b7bdbf
