color0 #211f1c
color1 #fd4663
color2 #a8a6a3
color3 #9c9a96
color4 #9c9c96
color5 #c1c0bd
color6 #c1c0bd
color7 #f3f2f2
color8 #6d6963
color9 #fd4663
color10 #a8a6a3
color11 #9c9a96
color12 #9c9c96
color13 #c1c0bd
color14 #c1c0bd
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #211f1c
background            #211f1c
foreground            #f3f2f2
selection_foreground  #b5b2b0
selection_background  #2c2926
active_border_color   #a8a6a3
inactive_border_color #2c2926
url_color             #a8a6a3

active_tab_foreground   #1e1c19
active_tab_background   #a8a6a3
inactive_tab_foreground #b5b2b0
inactive_tab_background #2c2926
cursor_trail_color      #b5b2b0
