color0 #e6e3e8
color1 #fd4663
color2 #27202b
color3 #29212a
color4 #292228
color5 #504158
color6 #544356
color7 #1a191a
color8 #887f8c
color9 #fd4663
color10 #27202b
color11 #29212a
color12 #292228
color13 #504158
color14 #544356
color15 #1a191a

cursor                #1a191a
cursor_text_color     #e6e3e8
background            #e6e3e8
foreground            #1a191a
selection_foreground  #535055
selection_background  #c8c2cb
active_border_color   #27202b
inactive_border_color #c8c2cb
url_color             #27202b

active_tab_foreground   #fafafa
active_tab_background   #27202b
inactive_tab_foreground #535055
inactive_tab_background #c8c2cb
cursor_trail_color      #535055
