# vim:fileencoding=utf-8

# configurar la tipografía
font_family JetBrainsMono Nerd Font Mono
bold_font 	 auto
italic_font	 auto
bold_italic_font auto
font_size 11

# el cursor es una linea
cursor_shape beam

# abrir siempre igual
remember_window_position no
remember_window_size  no
initial_window_width  85c
initial_window_height 25c

# layout
window_margin_width 5

# Transparencia de fondo
background_opacity 0.9

# === === Atajos === ===

# Abrir una división en el mismo lugar
map ctrl+shift+enter new_os_window_with_cwd
map f1 launch --cwd=current
map f2 launch --cwd=current --type=tab


