# vim:fileencoding=utf-8

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME

# Asegurarme de usar zsh
shell zsh

# configurar la tipografía
font_family JetBrainsMono Nerd Font Mono
bold_font 	 auto
italic_font	 auto
bold_italic_font auto
font_size 11

# abrir siempre igual
remember_window_position no
remember_window_size  no
initial_window_width  85c
initial_window_height 25c

# layout
window_margin_width 5

# === === Atajos === ===

# Abrir una división en el mismo lugar
map ctrl+shift+enter new_os_window_with_cwd
map f1 launch --cwd=current
map f2 launch --cwd=current --type=tab


